package com.doctorsoffice.doctor;

public enum MedicalSpecialization {

    ALLERGIST,
    ANESTHESIOLOGIST,
    CARDIOLOGIST,
    DERMATOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    NEUROLOGIST,
    NEPGROLOGIST,
    PULMONOLOGIST,
    ONCOLOGIST,
    OPHTHALMOLOGIST,
    ORTHOPEDIST,
    OTOLARYNGOLOGIST,
    PEDIATRICIAN,
    PODIATRIST,
    PSYCHIATRIST,
    RADIOLOGIST,
    RHEUMATOLOGIST,
    SURGEON,
    UROLOGIST

}
